# Generated by Django 4.2.3 on 2023-09-14 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0002_course_level_user_remove_reward_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='course_level',
        ),
        migrations.DeleteModel(
            name='user',
        ),
        migrations.AlterModelTable(
            name='reward',
            table='Reward',
        ),
    ]
