# Generated by Django 4.2.3 on 2023-10-02 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_account_info_remove_account_created_at_and_more'),
        ('Rewards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='User_ID',
            field=models.ForeignKey(db_column='User_ID', default=0, on_delete=django.db.models.deletion.CASCADE, to='login.account'),
        ),
    ]
