# Generated by Django 4.2.3 on 2023-10-02 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rewards', '0002_reward_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='User_ID',
        ),
    ]
