# Generated by Django 3.2.20 on 2023-10-09 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='Account',
        ),
    ]
