# Generated by Django 4.2.3 on 2023-09-14 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_account_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='ID',
            new_name='User_ID',
        ),
    ]
