<<<<<<< HEAD
# Generated by Django 3.2.20 on 2023-10-03 06:23

from django.db import migrations, models
=======
# Generated by Django 3.2.20 on 2023-09-22 07:35

from django.db import migrations, models
import django.db.models.deletion
>>>>>>> bf3ddc0bc369481e26652f928ec407fba3fa9cc3


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        ('login', '0004_profile'),
       # ('reward', '0004_auto_20230922_1550'),
>>>>>>> bf3ddc0bc369481e26652f928ec407fba3fa9cc3
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='userinformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=500, null=True)),
                ('img', models.ImageField(null=True, upload_to='images/')),
                ('residence', models.CharField(max_length=500, null=True)),
                ('goal', models.CharField(max_length=100, null=True)),
                ('weight', models.IntegerField(default=40, null=True)),
                ('attendance', models.DateField(auto_now=True, null=True)),
=======
            name='User_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=100, null=True)),
                ('img', models.ImageField(upload_to='images/')),
                ('attendance', models.DateField(auto_now=True)), 
                ('User_lev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reward.reward')),
>>>>>>> bf3ddc0bc369481e26652f928ec407fba3fa9cc3
            ],
        ),
    ]
