# Generated by Django 3.2.20 on 2023-10-10 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='nickname',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='residence',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
