# Generated by Django 4.2.3 on 2023-10-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0002_user_info_user_id_user_info_nickname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='User_lev',
        ),
        migrations.AddField(
            model_name='user_info',
            name='weight',
            field=models.IntegerField(default=40, null=True),
        ),
    ]
