# Generated by Django 3.2.20 on 2023-10-03 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0003_alter_userinformation_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userinformation',
            table='userinfo_userinformation',
        ),
    ]
