# Generated by Django 4.2.3 on 2023-10-02 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_delete_account_info_account_created_at_account_email_and_more'),
        ('userinfo', '0004_remove_user_info_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='User_ID',
            field=models.ForeignKey(db_column='User_ID', default=0, on_delete=django.db.models.deletion.CASCADE, to='login.account'),
        ),
    ]
