# Generated by Django 3.2.20 on 2023-10-09 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0004_alter_userinformation_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userinformation',
            table='userinfo',
        ),
    ]
