# Generated by Django 3.2.20 on 2023-10-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='collections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cRm_id', models.IntegerField(default=0, null=True)),
                ('cRm_Name', models.CharField(max_length=200, null=True)),
                ('cRm_color', models.CharField(max_length=200, null=True)),
                ('cRm_species', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
