# Generated by Django 4.2.6 on 2023-10-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Runningmate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rm_id', models.IntegerField(default=0, null=True)),
                ('Rm_Name', models.CharField(max_length=200, null=True)),
                ('Rm_color', models.CharField(max_length=200, null=True)),
                ('Rm_species', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'Runningmate',
            },
        ),
    ]
