# Generated by Django 4.2.3 on 2023-07-31 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseid', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('WLK_COURS_NM', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
