# Generated by Django 4.2.3 on 2023-08-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_course_courseid_remove_course_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='COURS_DC',
            field=models.TextField(null=True),
        ),
    ]
