# Generated by Django 4.2.3 on 2023-08-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_course_cours_dc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='COURS_SPOT_LA',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='COURS_SPOT_LO',
            field=models.FloatField(max_length=200, null=True),
        ),
    ]
