# Generated by Django 4.2.3 on 2023-08-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_course_cours_spot_la_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_r',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WLK_COURS_FLAG_NM', models.CharField(max_length=200, null=True)),
                ('WLK_COURS_NM', models.CharField(max_length=200, null=True)),
                ('COURS_LEVEL_NM', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'course_chuchun',
            },
        ),
    ]
