# Generated by Django 4.2.3 on 2023-08-16 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_course_r'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course_r',
        ),
    ]
