# Generated by Django 4.2.3 on 2023-09-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_remove_course_cours_lt_cn_remove_course_cvntl_nm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Runningmate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rm_Name', models.CharField(max_length=200, null=True)),
                ('Rm_color', models.CharField(max_length=200, null=True)),
                ('Rm_species', models.CharField(max_length=200, null=True)),
                ('Rm_category', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
