# Generated by Django 4.2.3 on 2023-09-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_runningmate_delete_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='runningmate',
            name='Rm_id',
            field=models.IntegerField(max_length=200, null=True),
        ),
    ]
