# Generated by Django 4.2.3 on 2023-09-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_runningmate_rm_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runningmate',
            name='Rm_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
