# Generated by Django 3.2.20 on 2023-09-22 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_alter_runningmate_rm_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runningmate',
            name='Rm_category',
        ),
    ]
