# Generated by Django 3.2.20 on 2023-10-05 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_runningmate_rm_level_alter_runningmate_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runningmate',
            name='Rm_level',
        ),
    ]
