# Generated by Django 4.2.6 on 2023-10-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Runrecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walk_count', models.IntegerField(default=0, null=True)),
                ('calorie', models.IntegerField(default=0, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('tatal_wc', models.IntegerField(default=0, null=True)),
            ],
            options={
                'db_table': 'Runrecord',
            },
        ),
    ]
