# Generated by Django 3.2.20 on 2023-10-10 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runrecord', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='runrecord',
            old_name='tatal_wc',
            new_name='total_wc',
        ),
    ]
